apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-prediction
  labels:
    app: package-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-prediction
  template:
    metadata:
      labels:
        app: package-prediction
    spec:
      containers:
      - name: package-prediction
        image: arunav934/package_prediction
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: package-prediction-service
  labels:
    app: package-prediction
spec:
  selector:
    app: package-prediction
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
